[options]
admin_passwd = $pbkdf2-sha512$600000$mBNijDEG4Nz739v7n/M.5w$wcFklH82vY6kYTIBc0b4bfJpsxL3vkRucPGAU13fGg9MCQwxSnexvMNzrojSw6XWuUbSzDf2R0qx43oQsi2oxw
addons_path = /mnt/extra-addons,/mnt/extra-addons/queue,/usr/lib/python3/dist-packages/odoo/addons
log_level = info
log_handler = :INFO,odoo.addons.mes_core:INFO
server_wide_modules = base,web,queue_job
workers = 2
queue_job__channels = root:2,root.maintainx:1
proxy_mode = True

